version: '2'

services:

  atsd:
    image: axibase/atsd:latest
    ports:
      - "8088:8088"
      - "8443:8443"
      - "8081:8081"
      - "8082:8082/udp"
    container_name: atsd
    hostname: atsd
    environment:
      - COLLECTOR_USER_NAME=collector
      - COLLECTOR_USER_PASSWORD=collector
      - COLLECTOR_USER_TYPE=api-rw
  collector1:
    image: axibase/collector:latest
    depends_on:
      - atsd
    ports:
      - "9443:9443"
    container_name: axibase-collector
    environment:
      - COLLECTOR_ARGS=-atsd-url=https://collector:collector@atsd:8443 -socrata-path=${DATASET_URL} -job-execute=socrata-auto
